language: java
sudo: false
install: true

dist: trusty

jdk:
- oraclejdk8

os:
- linux

branches:
  only:
  - anotherWayToFixSonar
  - master
#script:
#- ./gradlew build --scan -s

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/


cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

addons:
sonarcloud:
  organization: $SONARCLOUD_ORGANIZATION
  token:
    secure: $SONARCLOUD_TOKEN
script:
- ./gradlew assemble
- ./gradlew sonarqube -Dsonar.host.url=https://sonarcloud.io
- rm -rf .scannerwork

notifications:
  email:
    recipients:
    - bass-2000@yandex.ru
    on_success: always # default: change